alias: Garage automation
description: ""
triggers:
  - type: motion
    device_id: 31b15a8c48a0dc784c2c96a3fee76054
    entity_id: 4e224fee82119593a144cd6a747f04a0
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 0
      seconds: 0
conditions: []
actions:
  - action: camera.snapshot
    metadata: {}
    data:
      filename: /media/garage_notification.jpeg
    target:
      entity_id: camera.garage_camera_snapshot
  - action: camera.record
    metadata: {}
    data:
      duration: 60
      lookback: 0
      filename: >-
        /media/garage/garage_{{        
        now().astimezone().strftime('%Y-%m-%d-%H:%M:%S')}}.mp4
    target:
      entity_id: camera.garage_live
mode: single
