version: "3"
services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "1000:1000"
    ports:
      - 8080:8080
    volumes:
      - ${HOME}:/data
      - ${PWD}/config:/config
    restart: always
