services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    volumes:
      - ./homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    ports:
      - 8581:8581
      - 51081:51081/tcp
    environment:
      - TZ=America/Pacific
      - ENABLE_AVAHI=1
      - PGID=1099
      - PUID=1099
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
    network_mode: host
