services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    volumes:
      - ./homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    ports:
      - 8080:8080
      - 51803:51803/tcp
    environment:
      - TZ=America/Pacific
      - ENABLE_AVAHI=0
      - PGID=1099
      - PUID=1099
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
    network_mode: host
